MvcKutuphane/Controllers/DuyuruController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;


namespace MvcKutuphane.Controllers
{
    public class DuyuruController : Controller
    {
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        // GET: Duyuru
        public ActionResult Index()
        {
            var degerler = db.TBLDUYURU.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult DuyuruEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DuyuruEkle(TBLDUYURU t)
        {
            db.TBLDUYURU.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruSil(int id)
        {
            var duyuru = db.TBLDUYURU.Find(id);
            db.TBLDUYURU.Remove(duyuru);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruDetay(int id)
        {
            var duyuru = db.TBLDUYURU.Find(id);
            return View("DuyuruDetay", duyuru);
        }
        public ActionResult DuyuruGuncelle(TBLDUYURU t)
        {
            if (!ModelState.IsValid)
            {
                return View("DuyuruDetay");
            }
            var duyuru = db.TBLDUYURU.Find(t.ID);
            //db.Entry(t).State = System.Data.Entity.EntityState.Modified;
            duyuru.KATEGORI = t.KATEGORI;
            duyuru.ICERIK = t.ICERIK;
            duyuru.TARIH = t.TARIH;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Duyuru/DuyuruDetay.cshtml
@model MvcKutuphane.Models.Entity.TBLDUYURU
@{
    ViewBag.Title = "DuyuruDetay";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("DuyuruGuncelle", "Duyuru", FormMethod.Post, new { @class = "was-validated" }))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <label>Duyuru Numarası</label>
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control", placeholder = "ID", @disabled = "disabled" })
    </div>
    <div class="form-group">
        <label>Duyuru Kategorisi</label>
        @Html.TextBoxFor(k => k.KATEGORI, new { @class = "form-control", placeholder = "Kategori Adı", @required = "required" })
    </div>
    <div class="form-group">
        <label>Duyuru İçerik</label>
        @Html.TextAreaFor(k => k.ICERIK, new { @class = "form-control", placeholder = "İçerik", @required = "required" })
    </div>
    <div class="form-group">
        <label>Duyuru Tarih</label>
        @Html.TextBoxFor(k => k.TARIH, new { @class = "form-control", placeholder = "Tarih", @required = "required" })
    </div>
    <div>
        <button type="submit" class="btn btn-success">Güncelle</button>
    </div>
    @Html.HiddenFor(y => y.ID)
}

MvcKutuphane/Views/Duyuru/DuyuruEkle.cshtml
@model MvcKutuphane.Models.Entity.TBLDUYURU
@{
    ViewBag.Title = "DuyuruEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group was-validated" method="post">
    <div>
        <div class="form-group">
            <label>Duyuru Kategorisi</label>
            @Html.TextBoxFor(m => m.KATEGORI, new { @class = "form-control", placeholder = "Kategori Adı", @required = "required" })
            @Html.ValidationMessageFor(m => m.KATEGORI)
        </div>
        <div class="form-group">
            <label>Duyuru İçerik</label>
            @Html.TextBoxFor(m => m.ICERIK, new { @class = "form-control", placeholder = "İçerik", @required = "required" })
            @Html.ValidationMessageFor(m => m.ICERIK)
        </div>
        <div class="form-group">
            <label>Duyuru Tarih</label>
            @Html.TextBoxFor(m => m.TARIH, new { @class = "form-control", placeholder = "Tarih", @required = "required" })
            @Html.ValidationMessageFor(m => m.TARIH)
        </div>
        <div>
            <button type="submit" class="btn btn-success">Kaydet</button>
        </div>
    </div>

</form>

MvcKutuphane/Views/Duyuru/Index.cshtml
@using MvcKutuphane.Models.Entity;
@model List<TBLDUYURU>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<h2>Duyurular</h2>
<hr />
@Html.ActionLink("Yeni Duyuru", "DuyuruEkle", null, new { @class = "btn btn-dark" })
<br />
<br />
<br />
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Duyuru No</th>
            <th>Kategori Adı</th>
            <th>Tarih</th>
            <th class="not-export-col">Detaylar</th>
            <th class="not-export-col">Sil</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var duyuru in Model)
        {
        <tr>
            <td>@duyuru.ID</td>
            <td>@duyuru.KATEGORI</td>
            <td>@Convert.ToDateTime(duyuru.TARIH).ToString("dd/MMM/yyyy")</td>
            <td><a href="/Duyuru/DuyuruDetay/@duyuru.ID" class="btn btn-outline-dark">Görüntüle</a></td>
            <td><a href="/Duyuru/DuyuruSil/@duyuru.ID" class="btn btn-danger" onclick="return confirm('Silmek istiyor musunuz?')">Sil</a></td>
        </tr>
        }
    </tbody>
</table>