MvcKutuphane/Controllers/AdminLoginController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MvcKutuphane.Controllers
{
    public class AdminLoginController : Controller
    {
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        // GET: AdminLogin
        public ActionResult GirisYap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GirisYap(TBLPERSONEL personel)
        {
            var bilgiler = db.TBLPERSONEL.FirstOrDefault(x => x.KullaniciAdi == personel.KullaniciAdi && x.Sifre == personel.Sifre);
            if (bilgiler != null)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.KullaniciAdi, false);
                Response.Cookies["USER_ID"].Value = bilgiler.KullaniciAdi;
                Response.Cookies["USER_ID"].Expires = DateTime.Now.AddDays(1);
                Session["kullaniciAdi"] = bilgiler.KullaniciAdi;
                Session["personel"] = bilgiler.PERSONEL;
                Session["foto"] = bilgiler.Fotograf;
                Session["yetki"] = bilgiler.Rol;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["Kontrol"] = "Kullanıcı adı yada parola yanlış.";
                return View();
            }
        }

        public ActionResult CikisYap()
        {
            FormsAuthentication.SignOut();
            Response.Cookies["USER_ID"].Expires = DateTime.Now.AddDays(-1);
            return RedirectToAction("GirisYap");
        }
    }
}

MvcKutuphane/Views/AdminLogin/GirisYap.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Admin Login Sayfası</title>
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="~/Themes/AdminLogin/assets/css/login.css" rel="stylesheet" />
</head>
<body>
    <main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
        <div class="container">
            <div class="card login-card">
                <div class="row no-gutters">
                    <div class="col-md-5">
                        <img src="~/Themes/AdminLogin/assets/images/login.jpg" alt="login" class="login-card-img">
                    </div>
                    <div class="col-md-7">
                        <div class="card-body">
                            <div class="brand-wrapper">
                                <img src="~/Themes/AdminLogin/assets/images/logo.svg" alt="logo" class="logo">
                            </div>
                            <p class="login-card-description">Kütüphane Admin Paneli</p>
                            @if (TempData["Kontrol"] != null)
                            {
                                <div class="alert alert-danger">
                                    <strong>Dikkat!</strong> @TempData["Kontrol"]
                                </div>
                            }
                            @using (Html.BeginForm("GirisYap", "AdminLogin", FormMethod.Post, new { autocomplete = "off" }))
                            {
                                <div class="form-group">
                                    <label for="text" class="sr-only">Kullanıcı Adı</label>
                                    <input type="text" name="KullaniciAdi" id="email" class="form-control" placeholder="Kullanıcı Adınız" required="required">
                                </div>
                                <div class="form-group mb-4">
                                    <label for="password" class="sr-only">Parola</label>
                                    <input type="password" name="Sifre" id="password" class="form-control" placeholder="***********" required="required">
                                </div>
                                <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit" value="Giriş">
                            }
                            <a href="#!" class="forgot-password-link">Parolanı mı unuttun?</a> @*modal ile admine mail atsın bunun için bir rol eklemesi yapalım*@
                            @*<nav class="login-card-footer-nav">
                                <a>Panelimize hoşgeldiniz.</a>
                            </nav>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>